# See https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://forrestjacobs.com"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

smart_punctuation = true
