# See https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://forrestjacobs.com"

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"
