baseURL = 'https://forrestjacobs.com/'
languageCode = 'en-us'
timeZone = 'America/New_York'
title = 'Forrest Jacobs'
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[outputs]
home = ['html', 'rss']
section = ['html']

[outputFormats.RSS]
baseName = "rss"

[params]
description = "Forrest Jacobs’s personal technical blog."

[permalinks]
page.posts = '/:slug/'
section.posts = '/archive/'

[privacy.youTube]
privacyEnhanced = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Archive'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30
